[#kh-1]
== Chapter 1

[#kh-1-1]
=== Law 1
The months of the year are lunar months, as it is said: "[.add]#...# the burnt offering of the month in its month"footnote:[Bamidbar 28:14] and it is said: "This month shall be for you the head of the months"footnote:[Shemos 12:2]. This is what the sages said:
"The Holy One, blessed be He, showed to Moshe, in a prophetic vision, the image of the Moon, and said to him:
'[.add]#When# you see [.add]#the Moon# like this - sanctify [.add]#it#.'"footnote:[Rosh Hashanah 20b; Menachot 29a]

But the years that we reckon are solar years, as it is said: "Keep the month of aviv [.add]#spring#".footnote:[Dvarim 16]

[#kh-1-2]
=== Law 2
By how much is the solar year longer than the lunar year?
By approximately 11 days.
Therefore, when this excess accumulates to around 30 days, or a little less, or a little more,
a month is added and the year is made to have 13 months - which is called a "pregnant" year.
[.add]#This is done# because it is impossible to have a year of 12 months and some days,
as it is said: "for the months of the year" -
you count the months of the year, but not the days of the year.footnote:[Megilla 5a; Nazir 7a]

[#kh-1-3]
=== Law 3
Each month, the moon becomes hidden for about two days, or a little less or more:
about one day before its conjunction with the sun at the end of the month,
and about one day after its conjunction with the sun,
and in the evening it is sighted in the west.
The night when it is sighted in the west after being hidden is the beginning of the month.
We count 29 days from that day;
if the moon is sighted on the 30th night, the 30th day is the first day of the [.add]#next# month.
If it is not sighted, first day of the [.add]#next# month is the 31st day,
and the 30th day belongs to the previous month.
On the 31st night, we do not depend on the moon, regardless if it is visible or not,
since lunar month is never longer than 30 days.

[#kh-1-4]
=== Law 4
Month of 29 days, [.add]#when# the moon was sighted on the 30th night, is called "lacking".
If the moon was not sighted, and the previous month has 30 days,
it is called "pregnant" month, or "full" month.
The moon sighted on the 30th night is called "moon sighted on time".
If it is sighted on the 31st night, but not on the 30th night,
it is called "moon sighted on the night of pregnancy".

[#kh-1-5]
=== Law 5
Sighting of the moon is not up to an individual, unlike determination of the Shabbos,
where one counts 6 days and observes Shabbos on the 7th, but is given to the court. Only when the court sanctifies and
establishes the day as the beginning of the [.add]#new# month does it become the beginning of the [.add]#new# month.
As it is said: "this month shall be for you" - this testimony is entrusted to you.

[#kh-1-6]
=== Law 6
The court calculates, like the astronomers who know positions of the planets and their movements,
and look into it until they know if it is possible for the moon to be sighted on time - that is, on the 30th
night - or not. If they determined that it is possible for it to be sighted, they sit and wait for withnesses
all day - that is, the 30th day. If the witnesses did come and were examined in accordance with the law, and
their words were accepted - they sanctify it. If the moon was not sighted and the witnesses did not come,
they complete the 30 days and the month will be "pregnant". If they found out from calculations that it is
impossible to sight the moon, they do not sit during the 30th day and do not await the witnesses.
And if the witnesses did come, it is certain that they are false witnesses or that they saw a likeness of the
moon in the clouds and not the real moon.

[#kh-1-7]
=== Law 7
It is a positive commandment of the Torah for the court to calculate and to know whether the moon can
be sighted or not, and to examine the witnesses before the month is sanctified, and to send [.add]#messengers# to
notify the rest of the people which day is the beginning of the month, so that they know on which day are
the festivals. As it is said: "which you will call the holy convocations" and as it is said : "keep this
statute in its time".

[#kh-1-8]
=== Law 8
Calculation and establishment of the months and declaration of "pregnant" years is done only in the
Land of Israel, as it is said: "For out of Zion will come forth Torah, and the word of G-d - from Jerusalem".
But, if there was a man great in wisdom, and ordained in the Land of Israel, who came out of the Land, and
there remains no one equal to him in the Land of Israel, he can calculate and establish month, and declares
"pregnant" years outside of the Land. If he becomes aware that in the Land of Israel there appeared a man as great
as him - or, needless to say, greater than him - he is prohibited to establish and to proclaim outside of the Land,
and if he transgressed and did establish or did proclaim, it is as if he didn't do a thing.
