package org.podval.calendar.generate.chumash

// TODO load the names in various languages from the XML file

abstract class Parsha(number: Int)

object Parsha {
  case object Bereshit extends Parsha(1)
  case object Noach extends Parsha(2)
  case object LechLecha extends Parsha(3)
  case object Vayeira extends Parsha(4)
  case object ChayeiSarah extends Parsha(5)
  case object Toledot extends Parsha(6)
  case object Vayetze extends Parsha(7)
  case object Vayishlach extends Parsha(8)
  case object Vayeshev extends Parsha(9)
  case object Miketz extends Parsha(10)
  case object Vayigash extends Parsha(11)
  case object Vayechi extends Parsha(12)
  case object Shemot extends Parsha(13)
  case object Vaeira extends Parsha(14)
  case object Bo extends Parsha(15)
  case object Beshalach extends Parsha(16)
  case object Yitro extends Parsha(17)
  case object Mishpatim extends Parsha(18)
  case object Terumah extends Parsha(19)
  case object Tetzaveh extends Parsha(20)
  case object KiTisa extends Parsha(21)
  case object Vayakhel extends Parsha(22)
  case object Pekudei extends Parsha(23)
  case object Vayikra extends Parsha(24)
  case object Tzav extends Parsha(25)
  case object Shemini extends Parsha(26)
  case object Tazria extends Parsha(27)
  case object Metzora extends Parsha(28)
  case object AchareiMot extends Parsha(29)
  case object Kedoshim extends Parsha(30)
  case object Emor extends Parsha(31)
  case object Behar extends Parsha(32)
  case object Bechukotai extends Parsha(33)
  case object Bemidbar extends Parsha(34)
  case object Naso extends Parsha(35)
  case object Behaalotecha extends Parsha(36)
  case object Shlach extends Parsha(37)
  case object Korach extends Parsha(38)
  case object Chukat extends Parsha(39)
  case object Balak extends Parsha(40)
  case object Pinchas extends Parsha(41)
  case object Matot extends Parsha(42)
  case object Masei extends Parsha(43)
  case object Devarim extends Parsha(44)
  case object Vaetchanan extends Parsha(45)
  case object Eikev extends Parsha(46)
  case object Reeh extends Parsha(47)
  case object Shoftim extends Parsha(48)
  case object KiTeitzei extends Parsha(49)
  case object KiTavo extends Parsha(50)
  case object Nitzavim extends Parsha(51)
  case object Vayelech extends Parsha(52)
  case object Haazinu extends Parsha(53)
  case object VZotHaBerachah extends Parsha(54)
}
