[#problematic-nissan]
== Problematic Nissan (KH 6:7)
TODO

* day    1  5 107
*        1 12 793
* night  3  5 900

TODO split and sort the sources chronologically!

TODO re-verify the quotes.

TODO Describe what the standard edition is and where did it come from
(look it up in HebrewBooks.org, Sefaria).
Translate literally and with the original symbolic forms inserted.
Formulate the problem with the standard editions.

TODO laws and only laws; Rambam apologizes for the inclusion of the astronomical calendar,
but not for the inclusion of the description of the arithmetic operations like addition
and (later on) rounding. What about examples? Rambam did not just **formulate**
the laws (unambiguously; see rounding), his intention was for the reader to "know"
the laws, and examples are a part of that. This is the only example in the aritmetic part
of the text, but there are more in the astronomic one (all with years?).
What about the "simanim"?
It is much easier to add numbers than word expressions - compare side by side.
But only if the numbers are unambiguous: 17, not 5(in the daytime).
This particular example shows how to carry full days accumulated from hours during addition -
but only if the number is 17!

TODO either the word "in the daytime" is wrong, or the number "5".
Whoever notes the problem assume that the number is wrong.
It is clear from the actual calculation's result that if there is only one mistake,
it is the number.

TODO look carefully in all sources for yud/lamed prefices; see if the same system
is used by the same manuscripts in the astronomical part of the text.

TODO see if Yale/Moznaim abandons translating word forms later on.

Yale English translation (TODO) (example is split: Nisan in Law 6, the rest in Law 7):
> For example: Suppose the conjunction of Nisan occurred in the daytime
> of a Sunday the fifth hour and one hundred and seven parts of an hour‒in
> numerals: 1d 5h 107p.
> You proceed by adding to this the "character" of the lunar month,
> which is 1d 12h 793p, and find that the conjunction of Iyyar will occur
> at five hours and nine hundred parts on the night of Tuesday‒in
> numerals: 3d 5h 900p.
> And in the same manner you may proceed for month after month,
> until the end of time.

That is what all "standard" editions of the Rambam's text say,
even the modern ones like Eshkol, Pardes HaMelech.


Moznaim English translation (TODO):
> What is implied? If the conjunction [of the moon and the sun]
> for the month of Nisan takes place on Sunday, five hours and 107 units
> after sunrise
> (in numerical terms 1 - 5 - 107),
> by adding the reminder for a lunar month, 1 - 12 - 793, you will be able to
> determine that the conjunction of the month of Iyar will take place on
> Tuesday night, five hours and 900 units after nightfall
> (in numerical terms, 3 - 5 - 900).
> One may follow this same method [of calculation]
> month after month for eternity.

Moznaim (TODO) notes on the numerical expression for Nisan (note 6):
> Kinat Eliyahu suggests that the Rambam should have stated 1 - 17, since
> five hours after sunrise is seventeen hours after the beginning of the day.

Rambam LaAm (TODO) and Rambam Haaruch (TODO) do have notes,
but seem to work with the long-form values and ignore the Rambam's
"numerical forms" (and thus any issues with them) completely.

Kapach (1986) reflects the alternative splits into laws,
but ignores our issue.

Glitzenshtein (1993) writes:
> "5 hours in the daytime" - which are 17 hours from the beginning of the day

and proceeds with the calculations using the value 17
(TODO quote his calculations as an illustration why numerical expressions
must be assumption-free)

Hazak (2010) brings the question from the Rebbe's Yayin Malchut (52; but
they probably mean 43 - or did the numbers change in the 2016 edition?):
> why this example specifically, especially since this letter combination
> does not have any meaning?

HaRambam HaMevuar (2020) substantiates the expectation of 17 instead of 5
(TODO details) and notes (note 36):
> ... according to the note of Y. Ashkenazi on the Levush (Levush Adar HaYakar).
> Also, see compilation of the text variations in the Frenkel edition (RShF)
> that there are those who had the text say "1 - 17 - 107".

Frenkel TODO !!!

TODO translate the sicha

TODO search for the year

