[#solar-theory]
== Solar Theory
In his "Laws of the Sanctification of the Moon",  <<kh-12>>, <<kh-12-1>>, Rambam states: (TODO quote/reference)

In table format:
include::{tablesdir}/slm-printed.adoc[]


Now let's see if the printed values can be recovered by multiplying the value for one day by the number of days (and discarding full circles as appropriate):
include::{tablesdir}/slm-reconstructed.adoc[]

[#solar-model]
=== Model (TODO)
Figure out from the text directions of Sun's movements and what are the position angles from (look at the parallax correction stuff: subtract mean apogee from the mean Sun...).

TODO diagrams for the correction in Moznaim's Rambam.

[#exactification]
=== Exactification (TODO)
It is not clear how Rambam arrived at the values he gives.
When value of the movement in one day given by Rambam is multiplied by 29, 100 etc., the result is smaller than that of Rambam.
The following table compares printed and calculated values: TODO

Although the value of the movement of the mean solar longitude in one day given by <<Almagest>> III 1 (H209) (which, rounded to seconds, becomes Rambam's value) is bigger, it is not big enough, and Rambam's numbers (for more than 10 days) can not be explained by performing calculations with the long value from Almagest and then rounding the results to the precision of the Rambam's values.

<<Tzikuni>> (TODO p. XXX) gives the algorithm of such reconstruction: add to the remainder as many times 360 as there were full rotations in given time period, and then divide.
It also gives a value reconstructed from the printed values for 10,000, 1000 and 100 days: 59′8.33″, or 0.9856472 degrees, and the current "scientific" value of 0.9856473 degrees.
It seems that origins of the Rambam's value were questioned by his commentators, including "Pirush".
Value that can be derived from the tradition that 19 years = 6939 days 16 hours and 595 parts is 0.9856348.

This algorithm can be modified to produce an interval of possible values, taking into account precision of the numbers.

From the printed values it is possible to reconstruct the value of the movement in mean solar longitude in one day that Rambam used to calculate each of them:

Use it to calculate intervals for Rambam's values of the angular velocities.

<<Tzikuni>> quotes Rambam's value for 354 days as 348°55′15″, but calculated value as 348°55′9″, and notes that this "requires a little thought".

TODO About apogee, Rambam says "the same way", but doesn't give value for 1 day...
Exactification requires extra attention, since there is no value for 1 day.
SunApogee rambamValue and almagestValue.

[#solar-movement-29]
=== Angular movement for 29 days (TODO)
Are Rambam's values reconstructible if value for 29 days is calculated as 3*v(10)-v(1), not 2*v(10)+9*v(1), nor 29*vexact(1)?
For any tables other than SunLongitudeMean?

Values of the movement in one day apparently used by Rambam, if rounded to the seconds, give the "official" Rambam's value.
Values calculated from the value reconstructed from the printed 10000 days movement, if rounded, produce the values Rambam published - except for 29 days, 354 days, and 10000 days which we use to calculate the exact value that Rambam used!
TODO!

[#zeros]
=== Zeros (TODO)
Math.findZero(): Finish and test the code; use two separate lengths (precisions)?

[#sun-precise]
=== Sun for a precise time (TODO)
make possible calculations for a Moment, not just a Day (at least for the sun).

[#sun-creation]
=== Sun at Creation (TODO)
Where and when was the Sun created?
(Birchat Hachamo is on a different opinion.) Does it let us get more precise values of Sun's angular velocities?

[#true-seasons]
=== True seasons (TODO)
calculate true seasons in SeasonsAstronomical; KH 10:7 says that real vernal equinox is approximately two days before the mean one; add a test.

SeasonsAstronomical.seasonForYear: should this always be Nisan?

[#year-lengths]
=== Year lengths (TODO)
Convert each year length mentioned in the fixed calendar to angular speed.

What year length does value for mean anomaly velocity given by Moznaim correspond?

[#interesting]
=== Interesting
TODO От Корица: интересный линк на тему благословения на солнце и в конце обсуждение концепции Рамбама в астрономии - https://www.yeshiva.org.il/midrash/11088[]

[#interesting2]
=== Check statements of Nove Kadosh / Ibn Ezra
TODO От Корица:

ודבר זה הלכה למשה מסיני הוא, שבזמן שיש סנהדרין קובעין על הראייה ובזמן שאין שם סנהדרין קובעין על חשבון זה שאנו מחשבין בו היום ואין נזקקין לראייה, אלא פעמים שיהיה יום שקובעין בו בחשבון זה הוא יום הראייה או קודם לו ביום או אחריו ביום, וזה שיהיה אחר הראייה ביום פלא הוא ובארצות שהן למערב ארץ ישראל.

נאוה קודש הלכות קידוש החודש פרק ה הלכה ב כבר נתבאר לעיל בפרק ראשון הלכה ג' ע"פ ציור באיזה אופן שאפשר להיות קיבוץ האמתי קודם להאמצעי או שיהיה אחר האמצעי, ולפעמים יהיו קיבוץ האמתי והאמצעי ברגע אחד, והקדימה או האחירה של קיבוץ האמתי מהאמצעי לכל היותר הוא קרוב לי"ד שעות וכן דעת הר' אברהם אבן עזרא בפרשת בא דהיינו י"ג שעות ושלשה רביעיות שעה, ודוקא בתשרי אשר הוא במאזנים אזי אפשר שיקדים האמתי להאמצעי שיעור הנזכר אבל האיחור של קיבוץ האמתי מהאמצעי בתשרי לא יהיה כי אם קרוב לשש שעות ולא יותר ובחדש ניסן אשר הוא בטלה יהיה הדין בהפוך ר"ל לכל היותר לא תהיה הקדימה הנזכר כי אם קרוב לשש שעות, והאיחור יכול להיות קרוב לי"ד שעות, כל זה יתבאר בע"ה לקמן בדרך מופת, ומבואר שכל דברי רבינו של הלכה זו הולך וסובב על חדש תשרי אשר בו שייך כל הדחיות המבוארים לקמן בפרק ז' עיין שם,

Не знаю, кто это; не верю, что средневековцы могли доказать теорему о максимальной дистанции; но чтобы проверить эти утверждения, чьи бы они ни были, надо считать не только через 15 минут после захода, а в любой момент :)

ביוגרפיה - נאוה קדש רבי שמעון וואלטש היה מדרי העיר ברונשוויג שבאשכנז, את חכמת התכונה למד ממי שנחשב בדורו (שנות הת"ק) כאחד המומחים הגדולים בחכמה זו, הכונה לרבי ישכר בעריש בנו של הגאון הגדול רבי אריה ליב (בן הפנ"י) רבה הנודע של הנובר, אשר הסכים בהתלהבות לפרסום ספר "נאוה קודש", בפרט לאחר שכבר ניתנה הסכמתו של רבה הגדול של ברלין רבי צבי הירש לוין.
ספר "נאוה קודש" הודפס בברלין בשנת תקמ"ו (1786). 53 דף. הספר הודפס שנית במהדורת צילום (בתוך ספר פועל ה' ח"ב) בשנת תשכ"ט (1969), ושוב בבני ברק בשנת תשנ"ח (1998) (בתוך ספר פועל ה' ח"ג).
החידושים על הרמב"ם הוכנסו ממהדורת פרידברג ירושלים תשס"ו.

