[#solar-theory]
== Solar Theory

[#solar-theory-longitude]
=== Mean movement

In his "Laws of the Sanctification of the Moon", <<kh-12>>, <<kh-12-1>>, Rambam states:

[quote]
____
include::../kh/12-1.adoc[]
____

Simple reading of the text:

[quote]
movement in one day is ... it follows that movement in 10, 100, 1000, 10000 days is ... you can multiply and calculate movement for any number of days that you want ... movement for twenty-nine days and for three hundred and fifty-four ...

suggests the assumption:

_Values given by Rambam can be calculated by multiplying the value for one day that he gives by the number of days and discarding full circles as appropriate._

If this assumption was true, it would present a difficulty for those that read literally Rambam's statement in the introduction to "Mishne Torah" that he only includes laws in the text: values that can be calculated are redundant and should not be included!

As it turns out, the values Rambam gives can _not_ be calculated from the value for one day, as is clear from the following table, where the values given by Rambam are listed alongside the values calculated from the value for one day and the difference between them:

include::{tablesdir}/slm-printedAndCalculated.adoc[]

As we see, calculated values are smaller than the values Rambam gives, so the values that Rambam included in the text are not redundant - if, of course, they are used in the calculations; we'll look into that when reading <<kh-12>>, <<kh-12-2>> in the <<solar-theory-aphelion>> section below.  TODO wrong section

This prompts the change of assumption to:

_Values given by Rambam, including the value for one day, can be calculated by multiplying the *exact* value for one day that he does not give by the number of days, discarding full circles as appropriate and rounding the remainder up to the seconds._

The reading of the text then changes to:

[quote]
movement in one day [.add]#if rounded# is ... it follows that movement in 10, 100, 1000, 10000 days [.add]#calculated using the exact value and then rounded# is ... you can multiply [.add]#the exact value# and calculate movement for any number of days that you want ... movement for twenty-nine days and for three hundred and fifty-four [.add]#can also be calculated the same way# ...

Our goal is to extract as much information about the exact value Rambam used as possible _from the text itself_.
Of course, it is impossible to determine the exact value from the rounded results of multiplying it: the best we can do is to find the _interval_ of possible values for a given precision.

To find the interval of possible exact values for a given precision we:

- look for one value that reconstructs the values given by Rambam using step at the precision we want;
- if none is found, increase the precision (and thus decrease the step);
- construct an interval that contains just the value found;
- expand it at its precision using the appropriate step;
- expand it to the precision desired.

The code for this procedure, which is probably easier to understand than its description in words, is in https://github.com/opentorah/opentorah/blob/master/core/src/main/scala/org/opentorah/astronomy/Days2Rotation.scala[org.opentorah.astronomy.Days2Rotation].

Here are the intervals for the possible exact value that Rambam used extracted from the values he gives - with the least precision possible for each:

include::{tablesdir}/slm-exactMin.adoc[]

Precision sufficient for all of the values Rambam gives turns out to be up to the fourths; here are the intervals at that precision:

include::{tablesdir}/slm-exact.adoc[]

Contemplation of this table reveals a surprising fact: some pairs of the values are _incompatible_ in the sense that they can not be reconstructed from the same exact value by multiplication and rounding, and even though increasing the precision widens the intervals of the possible exact values, intervals for the incompatible values will never intersect, because there is a separating value for the pair such that the intervals of possible exact values are strictly on different sides of the separating value.
Here is a table that gives those separating values:

include::{tablesdir}/slm-compatibility.adoc[]

We can see that 29 is incompatible with 354, 1000 and 10000, and 354 is incompatible with 29, 100, 1000 and 10000; so, we have the following options:

[%autowidth]
|===
|option|reconstructed|exceptions

|1
|1, 10, 100, 1000, 10000
|29, 354

|2
|1, 10, 100, 29
|1000, 10000, 354

|3
|1, 10, 354
|100, 1000, 10000, 29

|===

Since we are looking for a reading with the most of the values reconstructed from the exact one and the fewest exceptions, we choose the first option; our assumption now becomes:

_Values given by Rambam, including the value for one day, can be calculated by multiplying the exact value for one day that he does not give by the number of days, discarding full circles as appropriate and rounding the remainder up to the seconds - except for the values for the month and the year, which can not be calculated this way._

Accordingly, our reading of the text changes to:

[quote]
movement in one day [.add]#if rounded# is ... it follows that movement in 10, 100, 1000, 10000 days [.add]#calculated using the exact value and then rounded# is ... you can multiply [.add]#the exact value# and calculate movement for any number of days that you want ... movement for twenty-nine days and for three hundred and fifty-four [.add]#can not be calculated this way# ...

Values for 29 and 354 are separated from the rest of the values in the text itself, and that is another argument (besides minimizing the number of exceptions) for choosing the reading where the exceptions are just 29 and 354: any other choice makes the reading even _more_ unnatural...

Intervals for 1, 10, 100, 1000 and 10000 days nest within one another, so any number in the interval for 10000 days reconstructs all of them.

For precision of four digits, that interval contains just one number: 0°59′8″19‴48′‴, so if the exact value Rambam used was of this precision (and not more precise; it could not have been less precise), it is this number.
In a sense, this number "falls out of the text".
Here are the values reconstructed from it, and how they compare with Rambam's values:

include::{tablesdir}/slm-printedAndCalculatedRambam.adoc[]

As expected, values for 29 and 354 are off.

It seems that ancient and medieval authors liked the precision of six sexagesimal digits (minutes, seconds, thirds, fourths, fifths, sixths), although it is not clear how meaningful is precision of less than 1/46 billionth of a degree in this context.
Here are the intervals for the exact values at precision of six digits:

include::{tablesdir}/slm-exact6.adoc[]

For our chosen interpretation, at this precision the exact value is in the interval from 0°59′8″19‴47′‴49″‴2‴‴ to 0°59′8″19‴48′‴10″‴37‴‴.

Now that we saw what the text itself tells us, let's see what classic and modern authors have to say about it; in the following, <<HaMevuar>> refers to the "in-depth analysis" in <<HaMevuar>> pp. 115-118. TODO remove this and add page references to all HaMevuar citations

The earliest remark that I am aware of belongs to <<Pirush>>:

[quote]
____
Movement in one day of 0°59′8″ is according to al-Battani, who in his book gives the value close to 0°59′8″20‴35′‴; but according to Btolemeus [.add]#= Ptolemy#, it is 0°59′8″17‴13′‴12″‴31‴‴.
For every opinion it corresponds with the length of the solar year on that opinion (which for Ptolemy is 365 and 1/4 days minus 1/300 of a day, and for al-Battani 365 and 1/4 days minus 3°40′ - where a day is 360°):
movement in one day is obtained by dividing 360° (full circle) by the length of the solar year.

Proof that Rambam follows al-Battani and not someone else is:
the value for 10 days that he gives - 9°51′23″ - is 3″ bigger than what it would have been - 9°51′20″ - if it was obtained as he suggests previously [.add]#by multiplying the value for 1 day that he gives by 10#; but since movement in one day is bigger than 0°59′8″ by 20‴, and multiplied by 10 they come to 200‴, he took out 180‴ of them as 3″ and added them to 20″, obtaining 23″; remaining 20‴ he multiplied by 10 and took out of them 3″ and added them to the value for 100 days, which he gives as 98°33′53″ [.add]#3″ more than the value he gives for 10 days (9°51′23″) multiplied by 10 (98°33′50″)#.
The same applies to the movement over a year and a month.
(The way to multiply is clear once the rules explained in chapter 11 are understood.)
____

If we calculate movement in one day from the length of the solar year that <<Pirush>> attributes to Ptolemy, we get the value that <<Pirush>> gives; for al-Battani, we get 0°59′8″21‴12′‴50″‴39‴‴, which is _not_ the value <<Pirush>> gives - there seems to be a mistake in <<Pirush>>'s calculation, as <<HaMevuar>> quotes Sefer HaZichronos noting.

Here is the comparison of the values reconstructed from the exact value that <<Pirush>> suggests with the values given by Rambam:

include::{tablesdir}/slm-printedAndCalculatedAlBattaniPirush.adoc[]

We see that the only values that are explained by the <<Pirush>>'s suggestion are the values for 1 and 10 days; everything else is off.

<<IbnHabib>> writes on <<Pirush>>:

[quote]
____
<<Pirush>>'s statement that Rambam follows al-Battani's calculations and that is the reason he adds 3″ to the value for 10 days seems to me to be true, correct and unassailable.
I have a difficulty, though: why didn't Rambam do the same with the value for 1000 days, where he should have also added 3″ resulting from [.add]#multiplying by 10# 20‴ remaining from the value for 100 days.
The same applies to the value for 10000 days: in current time, which is more than 126000 days after Rambam's epoch, resulting discrepancy in the position of the sun is 7′... I need to look into this.
I also have a difficulty with Rambam stating that movement of the sun during a regular year is 348°55′15″: it looks like Rambam added 7″ (TODO 2?) more than he should have based on the rate of movement mentioned.
I need to look into this; although some thoughts that provide partial explanation of the Rambam's text did occur to me, they are not yet complete in my mind - and that is why I did not write them down.
____

In the standard editions, in "3″ resulting from 20‴", 20‴ is misprinted as 2‴, which is hard to explain - unless it used to be written as a number instead of being spelled out, and somebody mistook chof for a bet. It is not clear to me how did IbnHabib arrive at the value 7′ for the discrepancy.

We see that <<IbnHabib>>:

* ignores the apparent mistake in the exact value suggested by <<Pirush>>
* questions the values for 1000, 10000, which <<Pirush>> doesn't claim as explained by his suggestion
* questions the value for 354, which <<Pirush>> does claim as explained
* affirms the value for 10 days
* does not mention the values for 100 and 29 days
* discrepancies that he quotes are not always the same as in the table above

We also see that <<Pirush>> and <<IbnHabib>> insist that Rambam must have copied his numbers from al-Battani (if he did not copy them from Ptolemy); some later authors (including <<LaAm>>) follow this opinion;
<<HaMevuar>> quotes some of the increasingly convoluted "explanations" of Rambams calculations that those authors produced while trying to preserve <<Pirush>>'s statements.

TODO why it is ok to disagree with Pirush.

<<HaMevuar>> credits <<Ajdler>> with quoting an alternative approach attributed to
some unnamed "later sages"; as far as I can tell, it is actually from
cite:[Neu83(398-399)], (p. 338-339 in the original publication)
(recapitulated in shorter and less aggressive form in <<Yale>>, p. 129):

[quote]
____
These values are not consistent with one another in the sense that they are not exact multiples of 0°59′8″. The obvious explanation is, of course, that we are dealing here with rounded off multiples of a more exact initial value.
Indeed, we can show even more.
The values for 1, 10 and 29 days and for 354 days (erroneously assumed to be an error by <<Baneth>> p. 43 note 5) are identical with the corresponding values in Al-Battani's tables, which, in turn are rounded off from multiples of 0°59′8″20‴46′‴56″‴14‴‴. The values for 100, 1,000 and 10,000 are not included in Al-Battani's tables but can be derived directly from them as follows.
We multiply the value for 30 days, given by Al-Battani as 29°34′10″, by 3 and add the value for 10 days, which is 9°51′23″. Then we obtain exactly Maimonides's value 98°33′53″. From this the values for 1,000 and for 10,000 days are obtained by multiplication by 10 and 100.

The insight into this procedure of Maimonides is historically not without interest.
In order to obtain the value for 100 days he simply took the rounded-off values for 30 and for 10 days, thus comitting an error 3ε1+ε2 if ε1 and ε2 are the errors of rounding off committed by Al-Battani.
This total error appears multiplied by 100 in the value for 10,000 days.
It is an amusing accident that the result agrees much better with modern values than any other value from Ptolemy to Copernicus.
<<Baneth>>, who did not realize how Maimonides's tables were constructed, praised this result "als ein glänzendes Ergebnis" [.add]#= a brilliant result# and conjectured that Maimonides compared observations of Al-Battani with results of Hipparchus.
We see now that Maimonides not only did not have the slightest intention to deviate from Al-Battani but that he showed the same disregard for the cumulative effect of errors which can be recognized in almost all ancient and mediaeval astronomers.
____

The following table compares the values Rambam gives with the calculations based on the al-Battani's exact value as given by <<Neugebauer>>:

include::{tablesdir}/slm-printedAndCalculatedAlBattaniNeugebauer.adoc[]

We see that the values for 100, 1000 and 10000 days can not be obtained by multiplying and then rounding the exact value derived from al-Battani, just as <<Neugebauer>> says - but neither is the value for 29 days what it should be, while <<Neugebauer>> lists it among those "rounded off from multiples" of the exact value for one day.

TODO 29 and 354 incompatible in al-Battani also?

<<Neugebauer>> p. 336 (396) says:
[quote]
Off hand, it is to be expected that Maimonides followed Arabic astronomers, even if he had Arabic translations of the Almagest at his disposal.
Indeed, we shall show that there exist very close relations between Maimonides and AI-Battani. ... We shall confirm this result for the whole theory of the solar and lunar movement. The theory of visibility, however, deviates from AI-Battani ... I do not know the source of this special section.

It seems that <<Neugebauer>> was so set in his preconception that Rambam must have copied his numbers from al-Battani, that all the proof he needed is the numbers in al-Battani being the same as the ones given by Rambam, even though, as we already know, Rambam's numbers (except for the 29 and 353 days) can be reconstructed from an exact value for one day that is *different* from al-Battani's! So, <<Neugebauer>>'s statements that Rambam:

* showed disregard for the cumulative effect of errors
* did not have the slightest intention to deviate from al-Battani
* obtained his value for 10000 days through an "amusing accident"

are incorrect unless Rambam indeed copied all the numbers from al-Battani and calculated the missing value for 100, 1000, and 10000 days the way <<Neugebauer>> describes - an assumption that is not supported by the text itself.

We focus on the Rambam's text itself, and feel no duty to satisfy any preconceived notions about the "history of ideas" and the "historical context"; we choose the reading that minimizes the number of values Rambam gives that can not be reproduced from an exact value for one day - and as we already saw, there is an interval of values that result in just two exceptions: 29 and 354 days.

We are not the first to choose this approach:

* <<HaMevuar>> ascribes it to Shvilei HaRakia, Nove Kodosh, Moer Hodosh, Shekel Hakodesh etc.
* <<Baneth>> seems to favor it.
* <<Moznaim>> also follows it: in 12:1 note 1, it quotes the value for one day as 0°59′8″19.8‴, which is 0°59′8″19‴48′‴; no references are given.
* <<Tzikuni>>, p. 44 also comes up with this value - if read charitably: the value he gives, 0°59′8.33″, which is 0°59′8″20‴, is not precise enough, but the floating point number he gives is; again, no references are given.
* <<Glitzenshtein>> also gives this number, and also without references.

On our approach, values for 29 and 354 days are exceptions not explained by multiplication and rounding; disturbingly, nobody writes that the value for 29 is an exception, not on the Rambam and not - lehavdil - on al-Battani. This needs attention ;)

<<HaMevuar>> quotes Moer Hodosh's suggestion that the value 348°55′15″ for 354 days got garbled during the transmission of the text, and should be corrected (restored) to 348°55′9″; <<Glitzenshtein>> gives an explanation of how such garbling happened.

<<HaMevuar>> quotes <<Ajdler>> questioning possibility of such corruption for the value for 354 days in all five angular velocity tables Rambam writes about - two for the sun and three for the moon.
This question becomes even stronger since 354 is not the only exception - 29 is another one.
Also, it is hard to explain even one occurrence of such corruption, since Rambam gives each number in both word and numeric forms.
At the same time, I do not think 354 is an exception in the second angular velocity table - the one we discuss in the following section, <<solar-theory-aphelion>>.

TODO move into a section after the aphelion movement is introduced

TODO quote opinions about the second movement being included in the table fro the first!

<<Pirush>> describes the correspondence between the length of the solar year and the movement of the sun in one day; since observable (true) movement of the sun is different from the mean one, it is not obvious to me that the correspondence described by <<Pirush>> is correct; nevertheless, let's bring together various opinions on the length of the solar year (and hence, angular velocity of the sun) that we encountered so far.

In the following table, the value that is primary according to the opinion (year length or velocity) is highlighted - TODO!.
We also list the values of the movement of the sun that Rambam gives that each opinion reconstructs correctly (by multiplication and rounding).
Opinion "al-Battani - Pirush (year)" uses the value for the length of the year that Pirush mentions (the one that does _not_ correspond the value for the velocity that he gives).

TODO describe and give sources for the opinions of Shmuel and Rav Ada

TODO quote the discourse about their opinions being incompatible with the text here
but used by the court for intercalation (that - from Sinai, this - reality)

include::{tablesdir}/slm-opinions.adoc[]

TODO move into the "Epoch" section

And one more thing: in the description of the arithmetic calendrical calculations (TODO where),
Rambam brings two opinions on the months when the world was created;
assuming that the sun was created at the start of the fourth day of creation,
and that it was at an equinox at the moment of its creation,
we can calculate the interval of possible exact values for the velocity of the sun
which will position it correctly at the Rambam's epoch (TODO reference):

include::{tablesdir}/slm-at-creation.adoc[]

[#solar-theory-aphelion]
=== Aphelion

In his <<kh-12>>, <<kh-12-2>>, Rambam continues:

[quote]
____
include::../kh/12-2-1.adoc[]
____

Here it is even more obvious that Rambam uses an exact value to calculate
the values he gives: he does not give the value for the movement in one day at all, so there is no way to calculate the values that he does give.

Value for 10 days, if multiplied by 10, gives the value for 100 days; values for 1000 and 10000 days can be obtained similarly.

include::{tablesdir}/sa-printedAndCalculated.adoc[]

Rambam does not give the value for one day, presumably because it is too small to matter
for our purposes, and he wants to simplify the calculations.
Straightforward criterion of being too small is: rounded up to a specific precision, the value becomes zero. Usually, everything in Rambam's text is rounded up to the seconds; here Rambam gives the value for ten days up to the _thirds_, so it would be natural to assume that his exact value for one day becomes zero when rounded up to the thirds - but any such value would then be too small to be usable to reconstruct the other values, so we are forced to say that the exact value becomes zero only when rounded up to the seconds.

We can use the same procedure as before to obtain the intervals
for the possible exact value that Rambam used from the values he gives;
here they are - with the least precision possible for each:

include::{tablesdir}/sa-exactMin.adoc[]

One number "jumps out of the text" (again):
we can reproduce all the values Rambam gives assuming that the exact value for one day that he used is 0°0′0″9‴.

include::{tablesdir}/sa-printedAndCalculatedRambam.adoc[]

Calculations show that it takes a bit less than 66 years for the aphelion to move one degree, not 70 years.

When we round the results of the calculations up to the thirds, the highest precision Rambam uses (in the value for ten days), we see some discrepancies:

include::{tablesdir}/sa-printedAndCalculatedRambam3.adoc[]

TODO need to see the effects of the rounding; compare with the explanations of Pirush above;
analyze the alternative presentation possibilities

TODO no answer for the redundancy question here

Here are the intervals for the exact values at precision of six digits:

include::{tablesdir}/sa-exact6.adoc[]

The interval for ten thousand days in nested within every other interval,
so all the values can be reconstructed based on any value from the interval from 0°0′0″8‴59′‴49″‴2‴‴ to 0°0′0″9‴0′‴10″‴37‴‴.

// TODO equation of centre