plugins {
  id 'java-library'
  id 'scala'
  id 'maven-publish'
  id 'signing'
  id 'org.podval.tools.scalajs'
}

description = 'Jewish Texts, Readings and Learning Schedules'

apply from: '../configure.gradle'

dependencies {
  implementation project(':opentorah-core')

//  implementation libs.logback
//  implementation libs.logstash
}
