plugins {
  id 'java-library'
  id 'scala'
  id 'org.podval.conventions.publish'
  id 'org.podval.tools.scala'
}

description = 'Jewish Texts, Readings and Learning Schedules'

apply from: '../configure.gradle'

dependencies {
  implementation project(':opentorah-core')

//  implementation libs.logback
//  implementation libs.logstash
}
