plugins {
  id 'java-library'
  id 'scala'
  id 'org.podval.tools.scalajs'
  id 'maven-publish'
  id 'signing'
}

description = 'Open Torah Core'

apply from: '../configure.gradle'

final String catsVersion = '2.13.0'

dependencies {
  // Substituted from the xml composite build when that checkout is present.
  api 'org.podval:org.podval.xml:0.0.2' // TODO api?!

  implementation 'com.kosherjava:zmanim:2.5.0'

  testImplementation "org.typelevel:cats-core_3:$catsVersion"
  testImplementation "org.typelevel:cats-laws_3:$catsVersion"
}
