plugins {
  id 'java-library'
  id 'scala'
  id 'org.podval.tools.scalajs'
  id 'maven-publish'
  id 'signing'
}

description = 'Open Torah Core'

apply from: '../configure.gradle'

dependencies {
  api libs.scala.xml
  api libs.zio.core
  api libs.zio.streams // TODO ?

  // Only when settings.gradle includeBuild found site-publisher (local layout).
  if (gradle.ext.has('includeSitePublisher') && gradle.ext.includeSitePublisher) {
    api libs.podval.xml
  }

  implementation libs.xerces

  implementation libs.zmanim

  // Optional dependencies:
  // - are declared here as 'compileOnly';
  // - need to be supplied as 'runtimeOnly' ('implementation'?) where needed.

  compileOnly libs.caffeine

  testImplementation libs.zio.test
  testImplementation libs.cats.core
  testImplementation libs.cats.laws
}
