<?xml version="1.0" encoding="UTF-8"?>
<!-- DO NOT EDIT! Generated by the DocBook plugin. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:import href="http://docbook.sourceforge.net/release/xsl-ns/current/epub/docbook.xsl"/>
  <xsl:import href="epub2-params.xsl"/>
  <xsl:import href="common-custom.xsl"/>
  <xsl:import href="htmlCommon-custom.xsl"/>
  <xsl:import href="epub2-custom.xsl"/>

  <xsl:param name="img.src.path">images/</xsl:param>
  <xsl:param name="base.dir">/home/dub/Projects/calendar/numbers-cleanup/paper/build/docBookTmp/epub2/</xsl:param>
  <xsl:param name="root.filename">calendar</xsl:param>
  <xsl:param name="epub.embedded.fonts"/>
</xsl:stylesheet>
