<?xml version="1.0" encoding="UTF-8"?>
<!-- DO NOT EDIT! Generated by the DocBook plugin.
     Customizations go into epub3-custom.xsl. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:param name="chunk.first.sections">1</xsl:param>
  <xsl:param name="epub.embedded.fonts"></xsl:param>
  <xsl:param name="use.id.as.filename">yes</xsl:param>
  <xsl:param name="section.autolabel">0</xsl:param>
  <xsl:param name="toc.section.depth">4</xsl:param>
  <xsl:param name="img.src.path">images/</xsl:param>
  <xsl:param name="base.dir">/home/dub/Projects/calendar/numbers-cleanup/paper/build/docBookTmp/epub3/</xsl:param>
  <xsl:param name="chunker.output.indent">yes</xsl:param>
  <xsl:param name="chunker.output.encoding">UTF-8</xsl:param>
  <xsl:param name="root.filename">calendar</xsl:param>
</xsl:stylesheet>
