<?xml version="1.0" encoding="UTF-8"?>
<!-- DO NOT EDIT! Generated by the DocBook plugin. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <!-- common -->
  <xsl:param name="toc.section.depth">4</xsl:param>
  <xsl:param name="section.autolabel">0</xsl:param>
  <xsl:param name="runinhead.default.title.end.punct"/>
  <!-- htmlCommon -->
  <xsl:param name="chunk.first.sections">1</xsl:param>
  <xsl:param name="chunk.quietly">1</xsl:param>
  <xsl:param name="use.id.as.filename">yes</xsl:param>
  <xsl:param name="chunker.output.indent">yes</xsl:param>
  <xsl:param name="chunker.output.encoding">UTF-8</xsl:param>
  <!-- html -->

</xsl:stylesheet>
