<?xml version="1.0" encoding="UTF-8"?>
<!-- DO NOT EDIT! Generated by the DocBook plugin. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
  <!-- html2 -->
  <xsl:param name="use.id.as.filename">yes</xsl:param>
  <xsl:param name="toc.section.depth">4</xsl:param>
</xsl:stylesheet>
