<?xml version="1.0" encoding="UTF-8"?>
<!-- DO NOT EDIT! Generated by the DocBook plugin.
     Customizations go into html2-custom.xsl. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:import href="https://cdn.docbook.org/release/latest/xslt/html/chunk.xsl"/>
  <xsl:import href="html2-params.xsl"/>
  <xsl:import href="html2-custom.xsl"/>
</xsl:stylesheet>
