<?xml version="1.0" encoding="UTF-8"?>
<!-- DO NOT EDIT! Generated by the DocBook plugin. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
  <xsl:import href="https://cdn.docbook.org/release/latest/xslt/html/chunk.xsl"/>
  <xsl:import href="html2-params.xsl"/>
  <xsl:import href="html2-custom.xsl"/>

  <xsl:param name="img.src.path">images/</xsl:param>
  <xsl:param name="base.dir">/home/dub/Projects/calendar/numbers-cleanup/paper/build/docBook/html2/</xsl:param>
  <xsl:param name="html.stylesheets">css/docBook.css</xsl:param>
</xsl:stylesheet>
