<?xml version="1.0" encoding="UTF-8"?>
<!-- DO NOT EDIT! Generated by the DocBook plugin. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <!-- common -->
  <xsl:param name="toc.section.depth">4</xsl:param>
  <xsl:param name="section.autolabel">0</xsl:param>
  <xsl:param name="runinhead.default.title.end.punct"/>
  <!-- pdf -->
  <xsl:param name="fop.extensions">0</xsl:param>
  <xsl:param name="body.font.master">12</xsl:param>
  <xsl:param name="body.font.family">DejaVu Sans</xsl:param>
  <xsl:param name="fop1.extensions">1</xsl:param>
  <xsl:param name="title.font.family">DejaVu Sans</xsl:param>
  <xsl:param name="draft.mode">no</xsl:param>
  <xsl:param name="double.sided">yes</xsl:param>
  <xsl:param name="monospace.font.family">DejaVu Sans Mono</xsl:param>
  <xsl:param name="sans.font.family">DejaVu Sans</xsl:param>
  <xsl:param name="paper.type">USletter</xsl:param>
  <xsl:param name="symbol.font.family">DejaVu Sans</xsl:param>
  <xsl:param name="orderedlist.label.width">2em</xsl:param>
</xsl:stylesheet>
