<?xml version="1.0" encoding="UTF-8"?>
<!-- DO NOT EDIT! Generated by the DocBook plugin.
     Customizations go into pdf-custom.xsl. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:param name="fop.extensions">0</xsl:param>
  <xsl:param name="keep.relative.image.uris">1</xsl:param>
  <xsl:param name="body.font.master">12</xsl:param>
  <xsl:param name="body.font.family">DejaVu Sans</xsl:param>
  <xsl:param name="fop1.extensions">1</xsl:param>
  <xsl:param name="section.autolabel">0</xsl:param>
  <xsl:param name="sans.font.family">DejaVu Sans</xsl:param>
  <xsl:param name="toc.section.depth">4</xsl:param>
  <xsl:param name="paper.type">USletter</xsl:param>
  <xsl:param name="img.src.path">images/</xsl:param>
  <xsl:param name="title.font.family">DejaVu Sans</xsl:param>
  <xsl:param name="body.start.indent">0pt</xsl:param>
  <xsl:param name="symbol.font.family">DejaVu Sans</xsl:param>
  <xsl:param name="orderedlist.label.width">2em</xsl:param>
  <xsl:param name="draft.mode">no</xsl:param>
  <xsl:param name="double.sided">1</xsl:param>
  <xsl:param name="monospace.font.family">DejaVu Sans Mono</xsl:param>
</xsl:stylesheet>
