<?xml version="1.0" encoding="UTF-8"?>
<!-- DO NOT EDIT! Generated by the DocBook plugin. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:import href="http://docbook.sourceforge.net/release/xsl-ns/current/fo/docbook.xsl"/>
  <xsl:import href="pdf-params.xsl"/>
  <xsl:import href="common-custom.xsl"/>
  <xsl:import href="pdf-custom.xsl"/>

  <xsl:param name="img.src.path">images/</xsl:param>
</xsl:stylesheet>
