[#acknowledgements]
[acknowledgments]
== Acknowledgements

I want to acknowledge people who contributed to the content of this work - and to the fact of its existence ;) If your name should be on this list but isn't, please forgive me: the omission is not intentional.

* Mordechai Goldin - for providing office space and computer equipment when I, as a Yeshiva student, had neither;
* Ilia Pomansky - for encouraging this work from its beginning in in 1991 and on;
* my wife Nina - for listening to my wild ideas, for her patience, and for help with math;
* my daughter Menucha Rochel - for assistance with the translation;
* Rabbi Michael Koretz - for stimulating discussions during our visit to Israel in 2005, encouragement, and extensive research into customs of Torah/Haftarah reading;
* Dr. Michael Partensky - for encouragement and advise;
* Dr. Peter Ofman - for asking questions that prodded me to revive this project in 2011, after years of hiatus;
* Aron Matskin - for a discussion during his visit on Rosh Chodesh Mar Cheshvan 2012;
* Rabbi Chaim Prus - for causing me to investigate which number does the year of Creation has - 0, 1 or 2;
