[#kh-14]
=== Chapter 14

[#kh-14-1]
==== Law 1
The moon has two mean movements. The moon itself rotates on a small circle
that does not surround all of the Earth. Moon's movement on that small circle is called <<mla-term>>. The small circle (epicycle TODO link to Wikipedia) itself rotates on a big circle (deferent TODO link to Wikipedia) that encircles the Earth. The mean movement of the small circle on the big circle that encircles the Earth is called movement of the <<mll-term>>.

[#kh-14-2]
==== Law 2
Movement in mean lunar longitude in one day is 13°10′35″footnote:[This is part of Law 1.].

For longer periods, (remainder) of the movement in mean lunar longitude is:

And in this way you can calculate it for any number of days and years that you want.

[#kh-14-3]
==== Law 3
Movement in mean lunar anomaly in one day is 13°3′54″.

For longer periods, (remainder) of the movement in mean lunar anomaly is:

[#kh-14-4]
==== Law 4
In the beginning of the night to Thursday that is the epoch (TODO measured from what? Chapter 11?) [TODO: link to definition]
for these calculations, mean lunar longitude was 1°14′43″ into the constellation of Ram.
And mean lunar anomaly on the epoch was 84°28′42″.
Now that you know rate of movement in the mean lunar longitude and its value on the epoch
to which you add, you'll calculate mean lunar longitude on any day that you want the same
way as you did for the mean solar longitude. TODO: reference

[#kh-14-5]
==== Law 5
After you calculate mean lunar longitude at the
beginning of the night that you want, contemplate the sun (TODO: longitude?) and figure out which
constellation (zodiac) is it infootnote:[This is part of Law 4.].
[This is the correction of the mean lunar longitude depending on
the mean solar longitude:]

[#kh-14-6]
==== Law 6
[%header, cols="1, 1, 1, 1"]
|===
|Solar Longitude on the Zodiac
|from
|to, not includingfootnote:[My understanding of the word usage in the original.]
|Lunar longitude correction

|middle of Pisces-middle of Taurusfootnote:[See Chapter 11, Law 7 on the start of Jewish Zodiac. (TODO reference)]
|315°
|15°
|0°

|middle of Taurus-beginning of Gemini
|15°
|30°
|0°15′

|beginning of Gemini-beginning of Leo
|30°
|90°
|0°15′

|beginning of Leo-middle of Virgo
|90°
|135°
|0°15′

|middle of Virgo-middle of Libra
|135°
|165°
|0°

|middle of Libra-beginning of Sagittarius
|165°
|210°
|-0°15′

|beginning of Sagittarius-beginning of Aquarius
|210°
|270°
|-0°30′

|beginning of Aquarius-middle of Pisces
|270°
|315°
|-0°15′

|===

The value of mean [lunar longitude]
after you add to it or subtract from it or leave it as
it is - that is mean lunar longitude approximately a third of an hour after sunset on the
date you are calculating it for. And this is what is called <<mllo-term>>.

