[#kh-summary]
== Rambam: Summary

[#kh-summary-general]
=== General.

[#kh-summary-1]
==== Chapter 1: Introduction.
* Law 1: Month is lunar; year is solar.
* Law 2: Solar year is ~11 days longer than the lunar; when discrepancy accumulates to ~30 days, year is made leap.
* Law 3: Moon is not seen for ~1 day before and after the conjunction;
first night when the Moon is sighted - Rosh Chodesh; next Rosh Chodesh:
if it is sighted on the night of the 30th day - 30th; if not - 31st.
* Law 4: Short/full month.
* Laws 5-8: Court calculates in a manner *resembling* the calculations of the astronomers.

[#kh-summary-2]
==== Chapter 2: Court procedure.
* Laws 1-10: Court procedure.

[#kh-summary-3]
==== Chapter 3: Court procedure.
* Laws 1-19: Court procedure; messengers.

[#kh-summary-4]
==== Chapter 4: Leap Year.
* Laws 1-2: Leap year - additional Adar;
Pesach (15th of Nisan) must in the spring: not before the day of vernal equinox
(Sun enters Aries, see 9:3) and before the next summer solstice.
* Laws 3-8: Other reasons for leaping the year;
(Succos after the autumnal equinox - not mentioned in Rambam.)
* Laws 9-17: Court procedure.

[#kh-summary-arithmetic]
=== Arithmetic calendar.

[#kh-summary-5]
==== Chapter 5: Introduction.
* Laws 1-2: Introduction; discrepancy with observations: -1…+1 day (+1 - very rare).
* Law 2: Fixed Rosh Hodesh: sighting of the Moon can be +/- 1 day; +2 - extremely rare.
* Law 3: When started.
* Laws 4-12: Second day of festivals.
* Law 13: Conclusion.

[#kh-summary-6]
==== Chapter 6: Conjunction. Lunar month and year. Leap year cycle.
* Law 1: "Molad" - approximate conjunction (Sun, Moon and Earth on the same line).
* Law 2: day = 24 hours; 1 hour = 1080 parts.
* Law 3: Lunar month (between conjunctions) = 29d12h793p.
* Law 4: Lunar year (12 lunar months) = 354d8h876p = 354d8h48m40s; Leap lunar year (13 lunar months) = 383d21h589p;
Solar year = 365d6h (see also 9:1, 10:6); longer than the lunar year by 10d21h204p.
* Law 5: Lunar month % 7 = 1d12h793p; lunar year % 7 = 4d8h876p; leap year % 7 = 5d21h589p.
* Law 7: if molad Nisan - Sunday, 5h107p after sunrise, next month - Iyar: Tuesday night, 5h900p.
* Law 8: First conjunction - Tishrei, year #1: Monday, 5h204p (just subtract % from the next one :))
Conjunction of Rosh Hashono of Adam's creation (year #2, see Shmita and Yovel 10:2): Friday, 6h.
* Law 9: We do not need the number of days, just the remainders.
* Law 10: 19 year cycle (12+7 leap); because the difference between 19 solar years and
the cycle is less than a day: 1h485p.
* Law 11: Leap years: 3,6,8,11,14,17,19.
* Law 12: cycle % 7 = 2d16h595p.

[#kh-summary-7]
==== Chapter 7: New Year corrections.
* Law 1: Rosh Hashono gets pushed off from Sunday, Wednesday, Friday.
* Law 2: Gets pushed off if molad is after noon (Molad Zoken).
* Law 3: ADU applies after noon push-off also.
* Law 4: Non-leap year, if molad is at night of the 3rd day after 9h204p: push off to Thursday (or the
year will be too long).
* Law 5: Year after leap one, Monday, after 5h589p: push to Tuesday.
* Law 7: ADU - why?

[#kh-summary-8]
==== Chapter 8: TODO
* Law 1: -> 6.3
* Law 2: Month - 29 or 30 days.
* Laws 5-6: Same?
* Law 7: TODO
* Law 8: TODO

[#kh-summary-9]
==== Chapter 9: Seasons.
* Law 2: 1/4 of the year between seasons (91d 7.5h).
* Law 3: Nisan (Spring) - Aries; Tammuz - Cancer; Tishrei - Libra; Teves - Cap.?
Vernal equinox of year #1 = 7d9h642p before conjunction of Nisan. Notes 5,7 in Moznaim edition.
Every year seasons move 30h; in 28 years - in the same place.
* Law 5: Vernal equinox, year 4930: midnight, 5th day, 8th of Nisan.
* Laws 6-8: Simplified procedure.
* Law 7: Real seasons - 2 days before average ones.
Note 5: 1st hour of the 4th day of creation; 1st vernal equinox.
Autumnal: Wednesday, 3 hours after daybreak, 1d23h before conjunction of Tishrei.

[#kh-summary-10]
==== Chapter 10: More precise length of the year. Seasons.
* Law 1: More precise length of a solar year. Moments.
* Law 2: Seasons for this year length.
* Law 3: Vernal equinox of year #1 - 9h642p before conjunction of Nisan.
(Different from 9:3: Rav Ada follows Rabbi Yehoshua - world created in Nisan;
Shmuel (9:3) follows Rabbi Eliezer - world created in Tishrei.)
Every first year of the 19-year cycle.
* Law 4: 1/4 of the year between seasons (91d7h519p31m).
* Law 5: Simplified procedure.
* Law 6: This more precise calculation of seasons was used by Sanhedrin to leap the year because of the spring equinox.
* Law 7: Real vernal equinox approximately 2 days before either of these calculations.

[#kh-summary-astronomical]
=== Atronomical Calculations.

[#kh-summary-11]
==== Chapter 11. Approximation. Angles. Mean and true motions. Epoch and location.
* Laws 1-4: Visibility calculations are deep. Fixed calendar can be appreciated even by school children in 3 or 4 days.
* Laws 5-6: Calculations are simplified/approximated to not fluster the inexperienced; result - visibility of the moon - is not affected.
* Laws 7-9: 360 degrees; 60 minutes, seconds...; order of the 12 constellations.
* Laws 10-12: adding/subtracting angles.
* Laws 13-14: Velocities are constant. Earth encircled by all the spheres but isn't in the center. Notes 14,15 in Moznaim.
* Law 15: Mean and true motion.
* Law 16: Epoch.
* Law 17: Location: Jerusalem; see Chapter 17.

[#kh-summary-12]
==== Chapter 12: Sun and its apogee.
* Law 1: Movement of the Sun. Moznaim Note 6: calculations may be accurate only on the first day of the month; Note 7.
59′8.33″ Yale, p.99; Neugeb., p. 388ff
* Law 2: Movement of the Sun's apogee. Moznaim Note 10: over 800 years, apogee moved ~12 degrees and is in constellation of Cancer.
Note 11: position - at 6PM.

[#kh-summary-13]
==== Chapter 13: True position of the sun. True seasons.
* Laws 1-3: True position of the Sun.
* Law 4: Course correction table.
* Laws 5-10: Examples.
* Law 11: True seasons.

[#kh-summary-14]
==== Chapter 14
* Law 1: Moon: epicycle and deferrent; movement as seen from Earth. See Moznaim notes!
* Law 2: Deferrent table.
* Law 3: Epicycle table.
* Law 4: Epoch.
* Law 5: Time of sighting correction table: ~20 minutes after sunset.

[#kh-summary-15]
==== Chapter 15
* Laws 1-2: Double elongation and its limits. See Moznaim notes!
* Laws 3-5: Course correction table.
* Laws 4-7: Parallax correction rules and table.
* Laws 8-9: Examples.

[#kh-summary-16]
==== Chapter 16
* Laws 1-4: Head movement, table and rules.
* Law 5: Example.
* Laws 6-18: Moon latitude.
* Law 19: Example.

[#kh-summary-17]
==== Chapter 17 (TODO)

[#kh-summary-18]
==== Chapter 18 (TODO)

[#kh-summary-19]
==== Chapter 19 (TODO)
