[#leap-years-cycle]
=== Meton's cycle
TODO
Show why 19-years cycle is the best.
Calculate optimal distribution of the leap years.

- 1:2 Solar year is ~11 days longer than the lunar (see chapter 6);
when discrepancy accumulates to ~30 days, year is made leap.
- 4:1-2 Leap year - additional Adar;
Pesach (15th of Nisan) must be not before the vernal equinox (Sun enters Aries, see 9:3)
and before the next summer solstice.

Moznaim:
Based on Sanhedrin 13a-b, the Ramah (cited in Kessef Mishneh on law 15):
"Succos must be after the autumnal equinox"; Rambam doesn't mention this.
With vernal equinox on Nissan 15th, autumnal could be on Tishrei 21st, 6 days into Succos.
Ohr Sameach: Rambam did say this, printers missed it.
Aruch HaShulchan: Rambam holds that that Sanhedrin isn't law; we only care about vernal equinox.

QUESTION: what are the properties of the fixed calendar in this respect
(need true seasons)?

- 6:3 Lunar month (between conjunctions) = 29d12h793p.
- 6:4 Lunar year (12 lunar months) = 354d8h876p = 354d8h48m40s;
Leap lunar year (13 lunar months) = 383d21h589p;
Solar year = 365d6h (see also 9:1, 10:6);
longer than the lunar year by 10d21h204p.
- 6:10 19 year cycle (12+7 leap); because the difference between 19 solar years and
the cycle is less than a day: 1h485p.
(see 10:1 - with a different year length, the difference is 0)

QUESTION: what other lengths of the cycle have this property?

- 6:11 Leap years: 3,6,8,11,14,17,19.

QUESTION: in what sense is this an optimal correspondence?
and for different cycle lengths? It is possible that true Sun calculations are needed to answer those questions...

Pirush in the beginning of Rambam -!!!
