package org.podval.docbook.gradle

import org.gradle.api.Project
import org.gradle.api.file.CopySpec
import java.io.File
import javax.xml.transform.stream.{StreamResult, StreamSource}
import org.apache.tools.ant.filters.ReplaceTokens
import org.xml.sax.InputSource
import scala.collection.JavaConverters._
import Util.writeInto

abstract class DocBook2 {

  def name: String

  def useDocBookXslt2: Boolean

  def usesHtml: Boolean

  def usesCss: Boolean

  def usesIntermediate: Boolean

  def stylesheetName: String

  def stylesheetUriName: String

  def outputDirectoryName: String
  def outputFileExtension: String

  def intermediateDirectoryName: String = outputDirectoryName
  def intermediateFileExtension: String = outputFileExtension

  protected final def getSaxonOutputDirectory(layout: Layout): File = {
    val forXslt: ForXslt = layout.forXslt(useDocBookXslt2)
    new File(
      if (usesIntermediate) forXslt.saxonOutputDirectoryRoot else forXslt.outputDirectoryRoot,
      if (usesIntermediate) intermediateDirectoryName else outputDirectoryName
    )
  }

  protected final def getSaxonOutputFile(layout: Layout, inputFileName: String): File = getOutputFile(
    getSaxonOutputDirectory(layout),
    inputFileName,
    if (usesIntermediate) intermediateFileExtension else outputFileExtension
  )

  private def getOutputFile(directory: File, inputFileName: String, extension: String): File =
    new File(directory, outputFileNameOverride.getOrElse(inputFileName) + "." + extension)

  final def writeStylesheetFiles(
    layout: Layout,
    inputFileName: String,
    parameters: Map[String, String],
    cssFileName: String,
    epubEmbeddedFonts: String,
    logger: Logger
  ): Unit = {
    val forXslt: ForXslt = layout.forXslt(useDocBookXslt2)
    val customStylesheetName: String = layout.customStylesheet(stylesheetName)
    val paramsStylesheetName: String = layout.paramsStylesheet(stylesheetName)

    // xsl:param has the last value assigned to it, so customization must come last;
    // since it is imported (so as not to be overwritten), and import elements must come first,
    // a separate "-param" file is written with the "default" values for the parameters :)

    writeInto(forXslt.stylesheetFile(layout.mainStylesheet(stylesheetName)), logger, replace = true) {
      s"""<?xml version="1.0" encoding="UTF-8"?>
         |<!-- DO NOT EDIT! Generated by the DocBook plugin.
         |     Customizations go into $customStylesheetName. -->
         |<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
         |  <xsl:import href="${forXslt.stylesheetUri}/$stylesheetUriName.xsl"/>
         |  <xsl:import href="$paramsStylesheetName"/>
         |  <xsl:import href="$customStylesheetName"/>
         |</xsl:stylesheet>
         |"""
    }

    // TODO I can handle htmlStylesheet here - exposing htmlStylesheetParameter from the processors...
    // and epub fonts too!
    val allParameters: Map[String, String] =
      Map("img.src.path" -> (layout.imagesDirectoryName + "/")) ++
      (if (!usesHtml) Map.empty else Map(
        "base.dir" -> (getSaxonOutputDirectory(layout).getAbsolutePath + "/"),
        "root.filename" -> Util.fileNameWithoutExtension(getSaxonOutputFile(layout, inputFileName))
      )) ++
      additionalParameters(
        layout = layout,
        htmlStylesheet = layout.cssFileRelative(cssFileName),
        epubEmbeddedFonts = epubEmbeddedFonts
      ) ++
      parameters

    writeInto(forXslt.stylesheetFile(paramsStylesheetName), logger, replace = true) {
      val parametersStr: String = allParameters.map { case (name: String, value: String) =>
        val valueEffective = if (value.isEmpty) "\"\"" else value
        s"""  <xsl:param name="$name">$valueEffective</xsl:param>"""
      }.mkString("\n")

      s"""<?xml version="1.0" encoding="UTF-8"?>
         |<!-- DO NOT EDIT! Generated by the DocBook plugin.
         |     Customizations go into $customStylesheetName. -->
         |<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
         |$parametersStr
         |</xsl:stylesheet>
         |"""
    }

    writeInto(forXslt.stylesheetFile(customStylesheetName), logger, replace = false) {
      s"""<?xml version="1.0" encoding="UTF-8"?>
         |<!-- Customizations go here. -->
         |<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
         |</xsl:stylesheet>
         |"""
    }
  }

  protected def additionalParameters(
    layout: Layout,
    htmlStylesheet: String,
    epubEmbeddedFonts: String
  ): Map[String, String]

  final def run(
    layout: Layout,
    isJEuclidEnabled: Boolean,
    inputFileName: String,
    substitutions: Map[String, String],
    resolver: Resolver,
    project: Project,
    logger: Logger
  ): Unit = {
    logger.info(s"\nProcessing DocBook to $name")

    val forXslt: ForXslt = layout.forXslt(useDocBookXslt2)

    // Saxon output directory and file.
    val saxonOutputDirectory: File = getSaxonOutputDirectory(layout)
    val saxonOutputFile: File = getSaxonOutputFile(layout, inputFileName)
    saxonOutputDirectory.mkdirs

    // Saxon
    Saxon.run(
      inputSource = new InputSource(layout.inputFile(inputFileName).toURI.toASCIIString),
      stylesheetSource = new StreamSource(forXslt.stylesheetFile(layout.mainStylesheet(stylesheetName))),
      outputTarget = new StreamResult(saxonOutputFile),
      resolver = resolver,
      processingInstructionsSubstitutions = substitutions,
      useXslt2 = useDocBookXslt2,
      logger = logger
    )

    val copyDestinationDirectory: File = Util.subdirectory(saxonOutputDirectory, copyDestinationDirectoryName)

    // Images.
    logger.info(s"Copying images")
    project.copy((copySpec: CopySpec) => copySpec
      .into(copyDestinationDirectory)
      .from(layout.imagesDirectory.getParentFile)
      .include(layout.imagesDirectoryName + "/**")
    )

    // CSS.
    if (usesCss) {
      logger.info(s"Copying CSS")
      project.copy((copySpec: CopySpec) => copySpec
        .into(copyDestinationDirectory)
        .from(layout.cssDirectory.getParentFile)
        .include(layout.cssDirectoryName + "/**")
        .filter(Map("tokens" -> substitutions.asJava).asJava, classOf[ReplaceTokens])
      )
    }

    // Post-processing.
    if (usesIntermediate) {
      logger.info(s"Post-processing $name")
      val outputDirectory: File = new File(forXslt.outputDirectoryRoot, outputDirectoryName)
      outputDirectory.mkdirs

      postProcess(
        layout = layout,
        useDocBookXslt2 = useDocBookXslt2,
        isJEuclidEnabled = isJEuclidEnabled,
        inputDirectory = saxonOutputDirectory,
        inputFile = saxonOutputFile,
        outputFile = getOutputFile(outputDirectory, inputFileName, outputFileExtension),
        logger = logger
      )
    }
  }

  def outputFileNameOverride: Option[String] = None

  def copyDestinationDirectoryName: Option[String] = None

  protected def postProcess(
    layout: Layout,
    useDocBookXslt2: Boolean,
    isJEuclidEnabled: Boolean,
    inputDirectory: File,
    inputFile: File,
    outputFile: File,
    logger: Logger
  ): Unit = {
  }
}

object DocBook2 {

  object Html extends DocBook2 {
    override def useDocBookXslt2: Boolean = false
    override def usesHtml: Boolean = true
    override def usesCss: Boolean = true
    override def usesIntermediate: Boolean = false

    override def name: String = "html"
    override def stylesheetName: String = "html"
    override def stylesheetUriName: String = "html/chunk"

    override def outputDirectoryName: String = "html"
    override def outputFileExtension: String = "html"
    override def outputFileNameOverride: Option[String] = Some("index")

    protected override def additionalParameters(
      layout: Layout,
      htmlStylesheet: String,
      epubEmbeddedFonts: String
    ): Map[String, String] = Map(
      "html.stylesheet" -> htmlStylesheet
    )
  }

  object Pdf extends DocBook2 {
    override def useDocBookXslt2: Boolean = false
    override def usesHtml: Boolean = false
    override def usesCss: Boolean = false
    override def usesIntermediate: Boolean = true

    override def name: String = "pdf"
    override def stylesheetName: String = "fo"
    override def stylesheetUriName: String = "fo/docbook"
    override def intermediateDirectoryName: String = "fo"
    override def intermediateFileExtension: String = "fo"
    override def outputDirectoryName: String = "pdf"
    override def outputFileExtension: String = "pdf"

    protected override def additionalParameters(
      layout: Layout,
      htmlStylesheet: String,
      epubEmbeddedFonts: String
    ): Map[String, String] = Map(
    )

    override protected def postProcess(
      layout: Layout,
      useDocBookXslt2: Boolean,
      isJEuclidEnabled: Boolean,
      inputDirectory: File,
      inputFile: File,
      outputFile: File,
      logger: Logger
    ): Unit = Fop.run(
      configurationFile = layout.fopConfigurationFile,
      isJEuclidEnabled = isJEuclidEnabled,
      inputFile = inputFile,
      baseDirectory = inputDirectory,
      outputFile = outputFile,
      logger = logger
    )
  }

  trait Epub extends DocBook2 {
    final override def usesHtml: Boolean = true
    final override def usesCss: Boolean = false
    final override def usesIntermediate: Boolean = true
    final override def outputFileExtension: String = "epub"
    final override def copyDestinationDirectoryName: Option[String] = Some("OEBPS")

    protected final override def additionalParameters(
     layout: Layout,
     htmlStylesheet: String,
     epubEmbeddedFonts: String
    ): Map[String, String] = Map(
      "html.stylesheet" -> htmlStylesheet,
      "epub.embedded.fonts" -> epubEmbeddedFonts
    )

    final override protected def postProcess(
      layout: Layout,
      useDocBookXslt2: Boolean,
      isJEuclidEnabled: Boolean,
      inputDirectory: File,
      inputFile: File,
      outputFile: File,
      logger: Logger
    ): Unit = {
      val zip = new org.apache.tools.ant.taskdefs.Zip
      zip.setProject(new org.apache.tools.ant.Project)
      zip.setPreserve0Permissions(true)
      zip.setCompress(false)
      zip.setDestFile(outputFile)
      val fileSet = new org.apache.tools.ant.types.FileSet()
      fileSet.setDir(inputDirectory)
      fileSet.appendIncludes(Array("mimetype", "META-INF/**", "OEBPS/**"))
      zip.addFileset(fileSet)
      zip.execute()
    }
  }

  object Epub2 extends Epub {
    override def name: String = "epub2"
    override def useDocBookXslt2: Boolean = false
    override def outputDirectoryName: String = "epub"
    override def stylesheetName: String = "epub"
    override def stylesheetUriName: String = "epub/docbook"
  }

  object Epub3 extends Epub {
    override def name: String = "epub3"
    override def useDocBookXslt2: Boolean = false
    override def outputDirectoryName: String = "epub3"
    override def stylesheetName: String = "epub3"
    override def stylesheetUriName: String = "epub3/chunk"
  }

  val forXslt1: List[DocBook2] = List(Html, Epub2, Epub3, Pdf)

  object Html2 extends DocBook2 {
    override def useDocBookXslt2: Boolean = true
    override def usesHtml: Boolean = true
    override def usesCss: Boolean = true
    override def usesIntermediate: Boolean = false

    override def name: String = "html"
    override def stylesheetName: String = "html"
    override def stylesheetUriName: String = "html/chunk" // TODO "html/html"?

    override def outputDirectoryName: String = "html"
    override def outputFileExtension: String = "html"
    override def outputFileNameOverride: Option[String] = Some("index")

    protected override def additionalParameters(
      layout: Layout,
      htmlStylesheet: String,
      epubEmbeddedFonts: String
    ): Map[String, String] = Map(
      "html.stylesheets" -> htmlStylesheet
    )
  }

  val forXslt2: List[DocBook2] = List(Html2)
}
