title: "the Open Torah Project"
description: "code, papers, books and historical documents"
url: "http://www.opentorah.org"
author: "Leonid Dubinsky"
email: dub@opentorah.org
timezone: "America/New_York"
favicon: favicon.ico

social:
  github:  dubinsky
  twitter: theopentorah
