plugins {
  id 'scala'
}

description = 'OpenTorah Documentation'

apply from: '../configure.gradle'

repositories {
  mavenCentral()
}

dependencies {
  implementation project(':opentorah-core')
  implementation libs.logback
}

final File buildDirectory = layout.buildDirectory.asFile.get()
final File tablesDir = file("$buildDirectory/tables")
tasks.register('generateTables', JavaExec) {
  group = 'documentation'
  outputs.dir(tablesDir)
  mainClass.set('org.opentorah.calendar.paper.Tables')
  args = [tablesDir]
  classpath = sourceSets.main.runtimeClasspath
}

tasks.named('build') {
  dependsOn(generateTables)
}
